### ISSUE TITLE
clean disconnection

### ISSUE THREAD

**Issue by MVidal80** [speed2exe/myzql-example#2]
Hi when trying this example: https://github.com/speed2exe/myzql-example/blob/main/src/main.zig
it works and I can connect to the mysql database and do selects

but when it exits (at every execution of the script) I get this error on the log file /var/log/mysql/error.log:

`2024-05-20  1:53:15 16077 [Warning] Aborted connection 16077 to db: 'xx' user: 'xx' host: 'localhost' (Got an error reading communication packets)
`

(even if stripping down everything from the script, leaving not even the 'ping')

I'm trying different languages, performing the same task
and I get this error only with Zig.

Can you please provide a 'clean' way to quit the connection ?

Thank you,
Vidal

**Comment by speed2exe** [comment]
@MVidal80 thanks for highlighting the issue. I wasn't aware of such. May I know which zig version and which myzql tags/commits you are using?

**Comment by MVidal80** [comment]
Hi yes sure
zig version: 0.12.0

```
        .url = "https://github.com/speed2exe/myzql/archive/refs/tags/0.0.9.tar.gz",
        .hash = "12203840d31971a3737e19b377e1f0f14dbacfeedb12cb433271f7e627098cef5668",

```

sorry i don't know if that answers the "tags/commits" part

**Comment by MVidal80** [comment]
cat build.zig

```
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const exe = b.addExecutable(.{
        .name = "myzql-example",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });
    b.installArtifact(exe);
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    // Add dependency here:
    const myzql_dep = b.dependency("myzql", .{});
    const myzql = myzql_dep.module("myzql");
    exe.root_module.addImport("myzql", myzql);
}

```

**Comment by MVidal80** [comment]
cat build.zig.zon 

```
.{
    .name = "myzql-example",
    .version = "0.0.1",
    .dependencies = .{ .myzql = .{
        .url = "https://github.com/speed2exe/myzql/archive/refs/tags/0.0.9.tar.gz",
        .hash = "12203840d31971a3737e19b377e1f0f14dbacfeedb12cb433271f7e627098cef5668",
    } },
    .paths = .{
        "build.zig",
        "build.zig.zon",
        "src",
    },
}

```

**Comment by MVidal80** [comment]
cat src/main.zig 

```
const std = @import("std");
const myzql = @import("myzql");
const Conn = myzql.conn.Conn;
const ResultSet = myzql.result.ResultSet;
const TextResultRow = myzql.result.TextResultRow;
const ResultRowIter = myzql.result.ResultRowIter;
const TextElemIter = myzql.result.TextElemIter;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();
    defer {
        switch (gpa.deinit()) {
            .ok => {},
            .leak => std.log.err("memory leak detected", .{}),
        }
    }

    var c = try Conn.init(allocator, &.{
        .username = "xx",
        .password = "xx",
        .database = "xx",
        .address = std.net.Address.initIp4(.{ 127, 0, 0, 1 }, 3306),
    });
    defer c.deinit();

    try c.ping();

}


```

**Comment by MVidal80** [comment]
Also pls let me know if you may be available for professional consulting
(spend few hours on improving this project and other Zig related tasks)
and I can contact you.

**Comment by speed2exe** [comment]
@MVidal80 thanks for the information! I'll look into it when I have the time. you may reach out to me through my email in my GitHub profile

**Comment by speed2exe** [comment]
@MVidal80 This issue be solved, from the recent commits. Feel free to reopen if issue persists.
